//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCaso1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public long Consecutivo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public int TipoMovimiento { get; set; }
    
        public virtual TiposMovimientos TiposMovimientos { get; set; }
    }
}
